apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-play-example
  labels:
    app: phpinfo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-play-example
  template:
    metadata:
      labels:
        app: kubernetes-play-example
    spec:
      containers:
      - name: kubernetes-play-example
        image: mrbbarton/kubernetes-play-example:1.0-SNAPSHOT
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-play-example-service
spec:
  type: NodePort
  selector:
    app: kubernetes-play-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009